#!/bin/bash
# Run devcontainer-dashboard using Docker Compose.
#
# Designed to be used as a one-liner:
#   curl -sL https://raw.githubusercontent.com/axelthas/devcontainer-dashboard/main/scripts/run-dashboard-compose.sh | bash
#
# The script writes a docker-compose.yml to ~/.config/devcontainer-dashboard/
# and starts the stack in the foreground.  Press Ctrl+C to stop.

set -euo pipefail

IMAGE="ghcr.io/axelthas/devcontainer-dashboard:latest"
CONFIG_DIR="${HOME}/.config/devcontainer-dashboard"
COMPOSE_FILE="${CONFIG_DIR}/docker-compose.yml"

# ── Prompt for workspace directory ───────────────────────────────────────────
# Read from /dev/tty so this works when the script is piped from curl.

DEFAULT_WORKSPACE="${HOME}/ddash-workspace"
printf 'Workspace directory [%s]: ' "${DEFAULT_WORKSPACE}" >/dev/tty
read -r WORKSPACE_ROOT </dev/tty
WORKSPACE_ROOT="${WORKSPACE_ROOT:-${DEFAULT_WORKSPACE}}"
# Expand a leading ~ to $HOME
WORKSPACE_ROOT="${WORKSPACE_ROOT/#\~/$HOME}"

mkdir -p "${WORKSPACE_ROOT}"

# ── Write docker-compose.yml ─────────────────────────────────────────────────

mkdir -p "${CONFIG_DIR}"

cat > "${COMPOSE_FILE}" <<EOF
# Generated by run-dashboard-compose.sh — edit to customise.
# Re-running the script overwrites this file.

services:
  dashboard:
    image: ${IMAGE}
    ports:
      - '3000:3000'
    environment:
      HOST_HOSTNAME: ${HOSTNAME:-}
      WORKSPACE_ROOT: ${WORKSPACE_ROOT}
      PRESETS_FILE: /data/presets.json
      VSCODE_SSH_HOST: \${VSCODE_SSH_HOST:-}
      # ── SSH for terminal sessions and dev-bootstrap cloning ─────────────────
      # Uncomment and set to your host agent socket path to forward SSH auth:
      # SSH_AUTH_SOCK: /tmp/ssh-agent.socket
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # Workspace root — must match WORKSPACE_ROOT above so devcontainer paths resolve correctly:
      - ${WORKSPACE_ROOT}:${WORKSPACE_ROOT}:rw
      - dashboard_data:/data
      # ── Persistent zsh history for the integrated terminal ──────────────────
      - ddash_zsh_data:/home/ddash/.zsh_data
      # ── SSH access (choose one or both) ─────────────────────────────────────
      # SSH agent socket — forward the host agent so clones and git ops work:
      # - \${SSH_AUTH_SOCK}:/tmp/ssh-agent.socket:ro
      # SSH key directory — alternative or complement to the agent socket:
      # - \${HOME}/.ssh:/home/ddash/.ssh:ro
      # ── dev-bootstrap setup hook (TernDev internal) ──────────────────────────
      # The hook script is bundled in the image at /opt/dashboard/hooks/.
      # Mount it into /docker-entrypoint.d/ to activate it on container start.
      # Requires SSH access (see above) to clone the private GitLab repository.
      # - /opt/dashboard/hooks/10-dev-bootstrap.sh:/docker-entrypoint.d/10-dev-bootstrap.sh:ro
      # ── Operator hooks (optional) ────────────────────────────────────────────
      # Drop additional executable .sh scripts into a host directory and mount it:
      # - \${HOME}/my-dashboard-hooks:/docker-entrypoint.d:ro
    restart: unless-stopped

volumes:
  dashboard_data:
  ddash_zsh_data:
EOF

echo "Compose file written to: ${COMPOSE_FILE}"
echo "Workspace:               ${WORKSPACE_ROOT}"
echo ""

# ── Pull + start ─────────────────────────────────────────────────────────────

echo "Pulling latest image..."
docker compose -f "${COMPOSE_FILE}" pull

echo ""
echo "Starting devcontainer-dashboard — press Ctrl+C to stop."
echo "Dashboard will be available at: http://localhost:3000"
echo ""
docker compose -f "${COMPOSE_FILE}" up
